[tool.ruff]
line-length = 119

[tool.ruff.lint]
ignore = [
    "E501",
    "W605",
]
select = [
    "E",
    "F",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"openmmforcefields/generators/__init__.py" = ["F401"]
"openmmforcefields/__init__.py" = ["F401"]
